### ISSUE TITLE
Cannot read property "status" of undefined.

### ISSUE THREAD

**Issue by rymaju** [Code-4-Community/lucys-love-bus#130]
![image](https://user-images.githubusercontent.com/23691775/110191427-65e70d80-7df6-11eb-87f2-d5ba94edb8c2.png)

**Comment by somya-p** [comment]
This error also occurs when a general member attempts to edit family information. 
Flow: Create account -> Account Settings -> Add or Edit Family Information -> Try to save -> Error
Note: the information I added actually is saved properly despite the surfacing of the error. Birthdate was saved as the day before what I entered though  
![image](https://user-images.githubusercontent.com/47909005/110722705-be485180-81e0-11eb-8282-4931e14e263a.png)

**Comment by jackblanc** [comment]
The listed error with editing family information is separate and fixed. 

I am unsure what specifically caused the event error, but it was not a size limit of 1MB. I can't reproduce this anymore, I've validated it locally, there were a few errors that were possibly related and all fixed. Look out for this in future.
