### ISSUE TITLE
Cannot edit events

### ISSUE THREAD

**Issue by rymaju** [Code-4-Community/lucys-love-bus#131]

**Comment by beccajohnson17** [comment]
One thing Kerry noted yesterday is that she tried to lower the available spaces of an existing event to 0 (as they've had outside registrations) and clicking "edit" isn't saving changes, so they are not reflected on the event after we try to edit it. This has been happening as well when they try to edit text- it's not saving.

**Comment by jackblanc** [comment]
fixed by https://github.com/Code-4-Community/lucys-love-bus-backend/commit/1fbcda67206f95dc4799e85be470fc3bfee9e0ed
