### ISSUE TITLE
Cannot post Annoucments without images

### ISSUE THREAD

**Issue by rymaju** [Code-4-Community/lucys-love-bus#140]
Currently getting a `Given parameter(s) post_announcement_request.imageSrc is (are) malformed` response

![image](https://user-images.githubusercontent.com/23691775/110724014-049eb000-81e3-11eb-8e98-8df118c4e1a9.png)

Currently sending:

```
{"title":"asdsa","description":"sads"}
```

We should make imageSrc optional on the backend or include a blank field here

**Comment by jackblanc** [comment]
Fixed by https://github.com/Code-4-Community/lucys-love-bus-backend/commit/0127a9b17277cb36ee3b2fe6aed9d23a4987f1af
