### ISSUE TITLE
Cannot Save Edited Family Information 

### ISSUE THREAD

**Issue by vrautela** [Code-4-Community/lucys-love-bus#141]
When editing family information as a general member, you cannot save your updated information even after filling in all required fields. This error is specifically encountered when adding a child.

![image](https://user-images.githubusercontent.com/16907452/110724102-2730c900-81e3-11eb-9ac6-145ac2a7fc2a.png)

**Comment by beccajohnson17** [comment]
this issue also happens with adult information for me, with the following error message: 
<img width="331" alt="Screen Shot 2021-03-10 at 8 49 27 PM" src="https://user-images.githubusercontent.com/44758803/110724752-614e9a80-81e4-11eb-9fdd-1e93758f1076.png">

**Comment by jackblanc** [comment]
Fixed by https://github.com/Code-4-Community/lucys-love-bus-backend/commit/3611f0d41db93757384dcfa901934fc576a00281
